typedef union fsFile;
typedef struct fsCdFile;
typedef struct fsMgcFile;
typedef struct fsMgfFile;
typedef struct fsHdFile;
typedef struct fsMgpFile;
typedef struct _anon0;
typedef union fsFileIndex;
typedef struct _anon1;


typedef char type_0[38];
typedef char type_1[44];
typedef fsFileIndex type_2[1];
typedef fsFileIndex type_3[1];
typedef fsFileIndex type_4[1];
typedef fsFileIndex type_5[1];
typedef char type_6[32];
typedef fsFile type_7[1];
typedef char type_8[45];
typedef fsFile type_9[1];
typedef char type_10[44];
typedef fsFileIndex type_11[1];
typedef fsFileIndex type_12[1];
typedef fsFileIndex type_13[1];
typedef fsFileIndex type_14[1];
typedef fsFile type_15[1];
typedef fsFileIndex type_16[1];
typedef fsFile type_17[1];
typedef fsFile type_18[1];
typedef char type_19[43];
typedef fsFile type_20[1];
typedef fsFile type_21[1];
typedef char type_22[46];
typedef fsFile type_23[1];
typedef char type_24[43];
typedef char type_25[44];
typedef fsFileIndex type_26[1];
typedef fsFileIndex type_27[1];
typedef char type_28[47];
typedef fsFileIndex type_29[1];
typedef fsFile type_30[1];
typedef fsFileIndex type_31[1];
typedef fsFile type_32[1];
typedef fsFile type_33[1];
typedef char type_34[43];
typedef char type_35[44];
typedef char type_36[41];
typedef fsFile type_37[1];
typedef fsFileIndex type_38[1];
typedef char type_39[44];
typedef fsFile type_40[1];
typedef fsFileIndex type_41[1];
typedef fsFile type_42[1];
typedef char type_43[45];
typedef fsFileIndex type_44[1];
typedef fsFileIndex type_45[1];
typedef fsFile type_46[1];
typedef char type_47[32];
typedef char type_48[43];
typedef fsFile type_49[1];
typedef fsFile type_50[1];
typedef char type_51[48];
typedef char type_52[43];
typedef char type_53[47];
typedef fsFile type_54[1];
typedef fsFileIndex type_55[1];
typedef fsFileIndex type_56[1];
typedef fsFileIndex type_57[1];
typedef char type_58[34];
typedef fsFileIndex type_59[1];
typedef fsFileIndex type_60[1];
typedef fsFileIndex type_61[1];
typedef fsFile type_62[1];
typedef fsFile type_63[1];
typedef char type_64[45];
typedef fsFile type_65[1];
typedef fsFile type_66[1];
typedef char type_67[47];
typedef char type_68[45];
typedef char type_69[43];
typedef fsFileIndex type_70[1];
typedef fsFile type_71[1];
typedef fsFileIndex type_72[1];
typedef fsFileIndex type_73[1];
typedef fsFileIndex type_74[1];
typedef fsFileIndex type_75[1];
typedef fsFile type_76[1];
typedef fsFile type_77[1];
typedef fsFile type_78[1];
typedef char type_79[43];
typedef char type_80[44];
typedef char type_81[42];
typedef fsFileIndex type_82[1];
typedef fsFile type_83[1];
typedef char type_84[41];
typedef fsFile type_85[1];
typedef char type_86[45];
typedef fsFileIndex type_87[1];
typedef char type_88[48];
typedef fsFileIndex type_89[1];
typedef fsFile type_90[1];
typedef char type_91[44];
typedef fsFile type_92[1];
typedef fsFileIndex type_93[1];
typedef fsFile type_94[1];
typedef fsFile type_95[1];
typedef fsFileIndex type_96[1];
typedef char type_97[47];
typedef char type_98[44];
typedef char type_99[38];
typedef fsFileIndex type_100[1];
typedef fsFileIndex type_101[1];
typedef fsFile type_102[1];
typedef fsFile type_103[1];
typedef char type_104[44];
typedef char type_105[34];
typedef fsFileIndex type_106[1];
typedef fsFileIndex type_107[1];
typedef fsFileIndex type_108[1];
typedef fsFile type_109[1];
typedef fsFileIndex type_110[1];
typedef fsFileIndex type_111[1];
typedef fsFile type_112[1];
typedef fsFile type_113[1];
typedef char type_114[46];
typedef fsFile type_115[1];
typedef char type_116[44];
typedef fsFileIndex type_117[1];
typedef fsFileIndex type_118[1];
typedef fsFileIndex type_119[1];
typedef fsFileIndex type_120[1];
typedef fsFile type_121[1];
typedef fsFile type_122[1];
typedef fsFile type_123[1];
typedef fsFileIndex type_124[1];
typedef char type_125[43];
typedef char type_126[44];
typedef char type_127[42];
typedef fsFile type_128[1];
typedef fsFile type_129[1];
typedef char type_130[46];
typedef char type_131[43];
typedef char type_132[44];
typedef fsFile type_133[1];
typedef fsFileIndex type_134[1];
typedef fsFileIndex type_135[1];
typedef char type_136[47];
typedef fsFileIndex type_137[1];
typedef fsFile type_138[1];
typedef fsFile type_139[1];
typedef fsFileIndex type_140[1];
typedef fsFile type_141[1];
typedef char type_142[43];
typedef char type_143[44];
typedef char type_144[41];
typedef fsFile type_145[1];
typedef fsFileIndex type_146[1];
typedef fsFileIndex type_147[1];
typedef fsFile type_148[1];
typedef char type_149[44];
typedef fsFile type_150[1];
typedef char type_151[45];
typedef char type_152[34];
typedef fsFileIndex type_153[1];
typedef fsFile type_154[1];
typedef fsFileIndex type_155[1];
typedef fsFile type_156[1];
typedef char type_157[43];
typedef fsFile type_158[1];
typedef char type_159[43];
typedef char type_160[47];
typedef char type_161[34];
typedef char type_162[47];
typedef fsFileIndex type_163[1];
typedef fsFileIndex type_164[1];
typedef fsFileIndex type_165[1];
typedef fsFileIndex type_166[1];
typedef fsFileIndex type_167[1];
typedef fsFile type_168[1];
typedef fsFileIndex type_169[1];
typedef fsFile type_170[1];
typedef char type_171[45];
typedef fsFile type_172[1];
typedef fsFile type_173[1];
typedef char type_174[40];
typedef char type_175[45];
typedef char type_176[47];
typedef fsFileIndex type_177[1];
typedef fsFile type_178[1];
typedef fsFileIndex type_179[1];
typedef fsFileIndex type_180[1];
typedef fsFileIndex type_181[1];
typedef fsFile type_182[1];
typedef fsFile type_183[1];
typedef fsFile type_184[1];
typedef char type_185[40];
typedef char type_186[44];
typedef char type_187[40];
typedef fsFile type_188[1];
typedef fsFileIndex type_189[1];
typedef fsFileIndex type_190[1];
typedef char type_191[41];
typedef fsFile type_192[1];
typedef char type_193[45];
typedef fsFileIndex type_194[1];
typedef fsFile type_195[1];
typedef fsFileIndex type_196[1];
typedef char type_197[48];
typedef char type_198[44];
typedef fsFile type_199[1];
typedef fsFileIndex type_200[1];
typedef char type_201[41];
typedef char type_202[47];
typedef fsFile type_203[1];
typedef fsFile type_204[1];
typedef fsFile type_205[1];
typedef char type_206[43];
typedef char type_207[34];
typedef fsFile type_208[1];
typedef fsFileIndex type_209[1];
typedef fsFileIndex type_210[1];
typedef fsFileIndex type_211[1];
typedef fsFileIndex type_212[1];
typedef fsFile type_213[1];
typedef fsFileIndex type_214[1];
typedef fsFile type_215[1];
typedef fsFile type_216[1];
typedef fsFile type_217[1];
typedef char type_218[46];
typedef char type_219[44];
typedef fsFileIndex type_220[1];
typedef fsFileIndex type_221[1];
typedef fsFileIndex type_222[1];
typedef fsFileIndex type_223[1];
typedef fsFile type_224[1];
typedef fsFile type_225[1];
typedef fsFile type_226[1];
typedef fsFileIndex type_227[1];
typedef char type_228[43];
typedef char type_229[44];
typedef char type_230[42];
typedef fsFile type_231[1];
typedef fsFile type_232[1];
typedef char type_233[43];
typedef char type_234[44];
typedef char type_235[47];
typedef fsFile type_236[1];
typedef fsFileIndex type_237[1];
typedef fsFile type_238[1];
typedef fsFileIndex type_239[1];
typedef fsFileIndex type_240[1];
typedef char type_241[47];
typedef char type_242[43];
typedef char type_243[44];
typedef fsFileIndex type_244[1];
typedef fsFile type_245[1];
typedef fsFile type_246[1];
typedef fsFileIndex type_247[1];
typedef fsFileIndex type_248[1];
typedef char type_249[44];
typedef fsFile type_250[1];
typedef char type_251[45];
typedef char type_252[34];
typedef fsFile type_253[1];
typedef fsFileIndex type_254[1];
typedef fsFileIndex type_255[1];
typedef fsFileIndex type_256[1];
typedef fsFileIndex type_257[1];
typedef fsFile type_258[1];
typedef char type_259[45];
typedef fsFile type_260[1];
typedef char type_261[32];
typedef char type_262[44];
typedef char type_263[47];
typedef fsFileIndex type_264[1];
typedef fsFileIndex type_265[1];
typedef fsFileIndex type_266[1];
typedef char type_267[21];
typedef fsFileIndex type_268[1];
typedef fsFileIndex type_269[1];
typedef fsFile type_270[1];
typedef fsFile type_271[1];
typedef fsFile type_272[1];
typedef char type_273[43];
typedef fsFileIndex type_274[1];
typedef fsFile type_275[1];
typedef fsFile type_276[1];
typedef fsFile type_277[1];
typedef char type_278[40];
typedef char type_279[45];
typedef char type_280[44];
typedef char type_281[47];
typedef fsFileIndex type_282[1];
typedef fsFileIndex type_283[1];
typedef fsFileIndex type_284[1];
typedef fsFile type_285[1];
typedef fsFileIndex type_286[1];
typedef fsFile type_287[1];
typedef fsFile type_288[1];
typedef fsFile type_289[1];
typedef fsFileIndex type_290[1];
typedef char type_291[40];
typedef char type_292[44];
typedef char type_293[40];
typedef fsFile type_294[1];
typedef fsFileIndex type_295[1];
typedef char type_296[44];
typedef fsFile type_297[1];
typedef char type_298[45];
typedef fsFile type_299[1];
typedef fsFileIndex type_300[1];
typedef fsFileIndex type_301[1];
typedef char type_302[44];
typedef fsFile type_303[1];
typedef fsFileIndex type_304[1];
typedef char type_305[48];
typedef char type_306[41];
typedef fsFile type_307[1];
typedef char type_308[32];
typedef fsFile type_309[1];
typedef char type_310[47];
typedef char type_311[43];
typedef fsFile type_312[1];
typedef fsFile type_313[1];
typedef fsFileIndex type_314[1];
typedef fsFileIndex type_315[1];
typedef fsFileIndex type_316[1];
typedef fsFileIndex type_317[1];
typedef fsFile type_318[1];
typedef fsFile type_319[1];
typedef fsFile type_320[1];
typedef char type_321[45];
typedef fsFileIndex type_322[1];
typedef fsFile type_323[1];
typedef char type_324[43];
typedef fsFileIndex type_325[1];
typedef fsFileIndex type_326[1];
typedef fsFileIndex type_327[1];
typedef fsFileIndex type_328[1];
typedef fsFile type_329[1];
typedef fsFile type_330[1];
typedef fsFile type_331[1];
typedef char type_332[43];
typedef fsFileIndex type_333[1];
typedef char type_334[44];
typedef char type_335[42];
typedef fsFile type_336[1];
typedef fsFile type_337[1];
typedef char type_338[43];
typedef char type_339[44];
typedef char type_340[47];
typedef fsFileIndex type_341[1];
typedef fsFileIndex type_342[1];
typedef fsFile type_343[1];
typedef fsFile type_344[1];
typedef char type_345[43];
typedef char type_346[44];
typedef char type_347[47];
typedef fsFile type_348[1];
typedef fsFileIndex type_349[1];
typedef fsFileIndex type_350[1];
typedef fsFileIndex type_351[1];
typedef fsFile type_352[1];
typedef char type_353[44];
typedef fsFile type_354[1];
typedef fsFile type_355[1];
typedef fsFileIndex type_356[1];

union fsFile
{
	_anon0 check;
	<unknown fundamental type (0xa510)> pack;
	fsCdFile cd;
	fsHdFile hd;
	fsMgcFile mgc;
	fsMgfFile mgf;
	fsMgpFile mgp;
};

struct fsCdFile
{
	struct
	{
		int type : 8;
		int number : 24;
	};
	char* name;
	int lsn;
	int size;
};

struct fsMgcFile
{
	struct
	{
		int type : 8;
		int padding : 24;
	};
	fsFile* parent;
	char* start;
	char* end;
};

struct fsMgfFile
{
	struct
	{
		int type : 8;
		int padding : 24;
	};
	fsFile* parent;
	int offset;
	int size;
};

struct fsHdFile
{
	struct
	{
		int type : 8;
		int padding : 24;
	};
	char* name;
	int offset;
	int size;
};

struct fsMgpFile
{
	struct
	{
		int type : 8;
		int padding : 24;
	};
	fsFile* file;
	fsMgcFile* start;
	fsMgcFile* end;
};

struct _anon0
{
	struct
	{
		int type : 8;
		int number : 24;
	};
	int pad0;
	int pad1;
	int pad2;
};

union fsFileIndex
{
	_anon1 index;
	unsigned long pack;
};

struct _anon1
{
	fsFile* fp;
	char* name;
};

char data_etc_message_mgf__name[21];
fsFile data_etc_message_mgf__info[1];
fsFileIndex data_etc_message_mgf[1];
char data_etc_message_common_msg_e_mes__name[34];
fsFile data_etc_message_common_msg_e_mes__info[1];
fsFileIndex data_etc_message_common_msg_e_mes[1];
char data_etc_message_common_msg_j_mes__name[34];
fsFile data_etc_message_common_msg_j_mes__info[1];
fsFileIndex data_etc_message_common_msg_j_mes[1];
char data_etc_message_item_msg_e_mes__name[32];
fsFile data_etc_message_item_msg_e_mes__info[1];
fsFileIndex data_etc_message_item_msg_e_mes[1];
char data_etc_message_item_msg_j_mes__name[32];
fsFile data_etc_message_item_msg_j_mes__info[1];
fsFileIndex data_etc_message_item_msg_j_mes[1];
char data_etc_message_m_card_msg_e_mes__name[34];
fsFile data_etc_message_m_card_msg_e_mes__info[1];
fsFileIndex data_etc_message_m_card_msg_e_mes[1];
char data_etc_message_m_card_msg_j_mes__name[34];
fsFile data_etc_message_m_card_msg_j_mes__info[1];
fsFileIndex data_etc_message_m_card_msg_j_mes[1];
char data_etc_message_memo_msg_e_mes__name[32];
fsFile data_etc_message_memo_msg_e_mes__info[1];
fsFileIndex data_etc_message_memo_msg_e_mes[1];
char data_etc_message_memo_msg_j_mes__name[32];
fsFile data_etc_message_memo_msg_j_mes__info[1];
fsFileIndex data_etc_message_memo_msg_j_mes[1];
char data_etc_message_option_msg_e_mes__name[34];
fsFile data_etc_message_option_msg_e_mes__info[1];
fsFileIndex data_etc_message_option_msg_e_mes[1];
char data_etc_message_option_msg_j_mes__name[34];
fsFile data_etc_message_option_msg_j_mes__info[1];
fsFileIndex data_etc_message_option_msg_j_mes[1];
char data_etc_message_stage_apart_boss_msg_e_mes__name[44];
fsFile data_etc_message_stage_apart_boss_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_apart_boss_msg_e_mes[1];
char data_etc_message_stage_apart_boss_msg_j_mes__name[44];
fsFile data_etc_message_stage_apart_boss_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_apart_boss_msg_j_mes[1];
char data_etc_message_stage_apart_e1f_msg_e_mes__name[43];
fsFile data_etc_message_stage_apart_e1f_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_apart_e1f_msg_e_mes[1];
char data_etc_message_stage_apart_e1f_msg_j_mes__name[43];
fsFile data_etc_message_stage_apart_e1f_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_apart_e1f_msg_j_mes[1];
char data_etc_message_stage_apart_e2f_msg_e_mes__name[43];
fsFile data_etc_message_stage_apart_e2f_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_apart_e2f_msg_e_mes[1];
char data_etc_message_stage_apart_e2f_msg_j_mes__name[43];
fsFile data_etc_message_stage_apart_e2f_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_apart_e2f_msg_j_mes[1];
char data_etc_message_stage_apart_e3fe_msg_e_mes__name[44];
fsFile data_etc_message_stage_apart_e3fe_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_apart_e3fe_msg_e_mes[1];
char data_etc_message_stage_apart_e3fe_msg_j_mes__name[44];
fsFile data_etc_message_stage_apart_e3fe_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_apart_e3fe_msg_j_mes[1];
char data_etc_message_stage_apart_e3fw_msg_e_mes__name[44];
fsFile data_etc_message_stage_apart_e3fw_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_apart_e3fw_msg_e_mes[1];
char data_etc_message_stage_apart_e3fw_msg_j_mes__name[44];
fsFile data_etc_message_stage_apart_e3fw_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_apart_e3fw_msg_j_mes[1];
char data_etc_message_stage_apart_out_msg_e_mes__name[43];
fsFile data_etc_message_stage_apart_out_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_apart_out_msg_e_mes[1];
char data_etc_message_stage_apart_out_msg_j_mes__name[43];
fsFile data_etc_message_stage_apart_out_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_apart_out_msg_j_mes[1];
char data_etc_message_stage_apart_stair_msg_e_mes__name[45];
fsFile data_etc_message_stage_apart_stair_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_apart_stair_msg_e_mes[1];
char data_etc_message_stage_apart_stair_msg_j_mes__name[45];
fsFile data_etc_message_stage_apart_stair_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_apart_stair_msg_j_mes[1];
char data_etc_message_stage_apart_w1f_msg_e_mes__name[43];
fsFile data_etc_message_stage_apart_w1f_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_apart_w1f_msg_e_mes[1];
char data_etc_message_stage_apart_w1f_msg_j_mes__name[43];
fsFile data_etc_message_stage_apart_w1f_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_apart_w1f_msg_j_mes[1];
char data_etc_message_stage_apart_w2f_msg_e_mes__name[43];
fsFile data_etc_message_stage_apart_w2f_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_apart_w2f_msg_e_mes[1];
char data_etc_message_stage_apart_w2f_msg_j_mes__name[43];
fsFile data_etc_message_stage_apart_w2f_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_apart_w2f_msg_j_mes[1];
char data_etc_message_stage_bowling_msg_e_mes__name[41];
fsFile data_etc_message_stage_bowling_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_bowling_msg_e_mes[1];
char data_etc_message_stage_bowling_msg_j_mes__name[41];
fsFile data_etc_message_stage_bowling_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_bowling_msg_j_mes[1];
char data_etc_message_stage_delusion_2_msg_e_mes__name[44];
fsFile data_etc_message_stage_delusion_2_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_delusion_2_msg_e_mes[1];
char data_etc_message_stage_delusion_2_msg_j_mes__name[44];
fsFile data_etc_message_stage_delusion_2_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_delusion_2_msg_j_mes[1];
char data_etc_message_stage_delusion_3_msg_e_mes__name[44];
fsFile data_etc_message_stage_delusion_3_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_delusion_3_msg_e_mes[1];
char data_etc_message_stage_delusion_3_msg_j_mes__name[44];
fsFile data_etc_message_stage_delusion_3_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_delusion_3_msg_j_mes[1];
char data_etc_message_stage_eddie_boss_msg_e_mes__name[44];
fsFile data_etc_message_stage_eddie_boss_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_eddie_boss_msg_e_mes[1];
char data_etc_message_stage_eddie_boss_msg_j_mes__name[44];
fsFile data_etc_message_stage_eddie_boss_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_eddie_boss_msg_j_mes[1];
char data_etc_message_stage_end_dog_msg_e_mes__name[41];
fsFile data_etc_message_stage_end_dog_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_end_dog_msg_e_mes[1];
char data_etc_message_stage_end_dog_msg_j_mes__name[41];
fsFile data_etc_message_stage_end_dog_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_end_dog_msg_j_mes[1];
char data_etc_message_stage_end_maria_msg_e_mes__name[43];
fsFile data_etc_message_stage_end_maria_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_end_maria_msg_e_mes[1];
char data_etc_message_stage_end_maria_msg_j_mes__name[43];
fsFile data_etc_message_stage_end_maria_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_end_maria_msg_j_mes[1];
char data_etc_message_stage_end_rebirth_msg_e_mes__name[45];
fsFile data_etc_message_stage_end_rebirth_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_end_rebirth_msg_e_mes[1];
char data_etc_message_stage_end_rebirth_msg_j_mes__name[45];
fsFile data_etc_message_stage_end_rebirth_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_end_rebirth_msg_j_mes[1];
char data_etc_message_stage_end_recovery_msg_e_mes__name[46];
fsFile data_etc_message_stage_end_recovery_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_end_recovery_msg_e_mes[1];
char data_etc_message_stage_end_recovery_msg_j_mes__name[46];
fsFile data_etc_message_stage_end_recovery_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_end_recovery_msg_j_mes[1];
char data_etc_message_stage_end_suicide_msg_e_mes__name[45];
fsFile data_etc_message_stage_end_suicide_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_end_suicide_msg_e_mes[1];
char data_etc_message_stage_end_suicide_msg_j_mes__name[45];
fsFile data_etc_message_stage_end_suicide_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_end_suicide_msg_j_mes[1];
char data_etc_message_stage_forest_msg_e_mes__name[40];
fsFile data_etc_message_stage_forest_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_forest_msg_e_mes[1];
char data_etc_message_stage_forest_msg_j_mes__name[40];
fsFile data_etc_message_stage_forest_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_forest_msg_j_mes[1];
char data_etc_message_stage_heaven_night_msg_e_mes__name[46];
fsFile data_etc_message_stage_heaven_night_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_heaven_night_msg_e_mes[1];
char data_etc_message_stage_heaven_night_msg_j_mes__name[46];
fsFile data_etc_message_stage_heaven_night_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_heaven_night_msg_j_mes[1];
char data_etc_message_stage_hospital_1f_f_msg_e_mes__name[47];
fsFile data_etc_message_stage_hospital_1f_f_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_hospital_1f_f_msg_e_mes[1];
char data_etc_message_stage_hospital_1f_f_msg_j_mes__name[47];
fsFile data_etc_message_stage_hospital_1f_f_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_hospital_1f_f_msg_j_mes[1];
char data_etc_message_stage_hospital_1fe_b_msg_e_mes__name[48];
fsFile data_etc_message_stage_hospital_1fe_b_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_hospital_1fe_b_msg_e_mes[1];
char data_etc_message_stage_hospital_1fe_b_msg_j_mes__name[48];
fsFile data_etc_message_stage_hospital_1fe_b_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_hospital_1fe_b_msg_j_mes[1];
char data_etc_message_stage_hospital_1fw_b_msg_e_mes__name[48];
fsFile data_etc_message_stage_hospital_1fw_b_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_hospital_1fw_b_msg_e_mes[1];
char data_etc_message_stage_hospital_1fw_b_msg_j_mes__name[48];
fsFile data_etc_message_stage_hospital_1fw_b_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_hospital_1fw_b_msg_j_mes[1];
char data_etc_message_stage_hospital_2f_b_msg_e_mes__name[47];
fsFile data_etc_message_stage_hospital_2f_b_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_hospital_2f_b_msg_e_mes[1];
char data_etc_message_stage_hospital_2f_b_msg_j_mes__name[47];
fsFile data_etc_message_stage_hospital_2f_b_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_hospital_2f_b_msg_j_mes[1];
char data_etc_message_stage_hospital_2f_f_msg_e_mes__name[47];
fsFile data_etc_message_stage_hospital_2f_f_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_hospital_2f_f_msg_e_mes[1];
char data_etc_message_stage_hospital_2f_f_msg_j_mes__name[47];
fsFile data_etc_message_stage_hospital_2f_f_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_hospital_2f_f_msg_j_mes[1];
char data_etc_message_stage_hospital_3f_b_msg_e_mes__name[47];
fsFile data_etc_message_stage_hospital_3f_b_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_hospital_3f_b_msg_e_mes[1];
char data_etc_message_stage_hospital_3f_b_msg_j_mes__name[47];
fsFile data_etc_message_stage_hospital_3f_b_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_hospital_3f_b_msg_j_mes[1];
char data_etc_message_stage_hospital_3f_f_msg_e_mes__name[47];
fsFile data_etc_message_stage_hospital_3f_f_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_hospital_3f_f_msg_e_mes[1];
char data_etc_message_stage_hospital_3f_f_msg_j_mes__name[47];
fsFile data_etc_message_stage_hospital_3f_f_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_hospital_3f_f_msg_j_mes[1];
char data_etc_message_stage_hospital_bf_b_msg_e_mes__name[47];
fsFile data_etc_message_stage_hospital_bf_b_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_hospital_bf_b_msg_e_mes[1];
char data_etc_message_stage_hospital_bf_b_msg_j_mes__name[47];
fsFile data_etc_message_stage_hospital_bf_b_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_hospital_bf_b_msg_j_mes[1];
char data_etc_message_stage_hospital_pass_msg_e_mes__name[47];
fsFile data_etc_message_stage_hospital_pass_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_hospital_pass_msg_e_mes[1];
char data_etc_message_stage_hospital_pass_msg_j_mes__name[47];
fsFile data_etc_message_stage_hospital_pass_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_hospital_pass_msg_j_mes[1];
char data_etc_message_stage_hospital_rf_f_msg_e_mes__name[47];
fsFile data_etc_message_stage_hospital_rf_f_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_hospital_rf_f_msg_e_mes[1];
char data_etc_message_stage_hospital_rf_f_msg_j_mes__name[47];
fsFile data_etc_message_stage_hospital_rf_f_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_hospital_rf_f_msg_j_mes[1];
char data_etc_message_stage_hotel_1f_b_msg_e_mes__name[44];
fsFile data_etc_message_stage_hotel_1f_b_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_hotel_1f_b_msg_e_mes[1];
char data_etc_message_stage_hotel_1f_b_msg_j_mes__name[44];
fsFile data_etc_message_stage_hotel_1f_b_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_hotel_1f_b_msg_j_mes[1];
char data_etc_message_stage_hotel_1f_f_msg_e_mes__name[44];
fsFile data_etc_message_stage_hotel_1f_f_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_hotel_1f_f_msg_e_mes[1];
char data_etc_message_stage_hotel_1f_f_msg_j_mes__name[44];
fsFile data_etc_message_stage_hotel_1f_f_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_hotel_1f_f_msg_j_mes[1];
char data_etc_message_stage_hotel_2f_b_msg_e_mes__name[44];
fsFile data_etc_message_stage_hotel_2f_b_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_hotel_2f_b_msg_e_mes[1];
char data_etc_message_stage_hotel_2f_b_msg_j_mes__name[44];
fsFile data_etc_message_stage_hotel_2f_b_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_hotel_2f_b_msg_j_mes[1];
char data_etc_message_stage_hotel_2f_f_msg_e_mes__name[44];
fsFile data_etc_message_stage_hotel_2f_f_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_hotel_2f_f_msg_e_mes[1];
char data_etc_message_stage_hotel_2f_f_msg_j_mes__name[44];
fsFile data_etc_message_stage_hotel_2f_f_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_hotel_2f_f_msg_j_mes[1];
char data_etc_message_stage_hotel_3f_b_msg_e_mes__name[44];
fsFile data_etc_message_stage_hotel_3f_b_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_hotel_3f_b_msg_e_mes[1];
char data_etc_message_stage_hotel_3f_b_msg_j_mes__name[44];
fsFile data_etc_message_stage_hotel_3f_b_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_hotel_3f_b_msg_j_mes[1];
char data_etc_message_stage_hotel_3f_f_msg_e_mes__name[44];
fsFile data_etc_message_stage_hotel_3f_f_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_hotel_3f_f_msg_e_mes[1];
char data_etc_message_stage_hotel_3f_f_msg_j_mes__name[44];
fsFile data_etc_message_stage_hotel_3f_f_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_hotel_3f_f_msg_j_mes[1];
char data_etc_message_stage_hotel_bf_b_msg_e_mes__name[44];
fsFile data_etc_message_stage_hotel_bf_b_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_hotel_bf_b_msg_e_mes[1];
char data_etc_message_stage_hotel_bf_b_msg_j_mes__name[44];
fsFile data_etc_message_stage_hotel_bf_b_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_hotel_bf_b_msg_j_mes[1];
char data_etc_message_stage_hotel_bf_f_msg_e_mes__name[44];
fsFile data_etc_message_stage_hotel_bf_f_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_hotel_bf_f_msg_e_mes[1];
char data_etc_message_stage_hotel_bf_f_msg_j_mes__name[44];
fsFile data_etc_message_stage_hotel_bf_f_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_hotel_bf_f_msg_j_mes[1];
char data_etc_message_stage_hotel_fire_msg_e_mes__name[44];
fsFile data_etc_message_stage_hotel_fire_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_hotel_fire_msg_e_mes[1];
char data_etc_message_stage_hotel_fire_msg_j_mes__name[44];
fsFile data_etc_message_stage_hotel_fire_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_hotel_fire_msg_j_mes[1];
char data_etc_message_stage_labyrinth_e_msg_e_mes__name[45];
fsFile data_etc_message_stage_labyrinth_e_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_labyrinth_e_msg_e_mes[1];
char data_etc_message_stage_labyrinth_e_msg_j_mes__name[45];
fsFile data_etc_message_stage_labyrinth_e_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_labyrinth_e_msg_j_mes[1];
char data_etc_message_stage_labyrinth_n_msg_e_mes__name[45];
fsFile data_etc_message_stage_labyrinth_n_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_labyrinth_n_msg_e_mes[1];
char data_etc_message_stage_labyrinth_n_msg_j_mes__name[45];
fsFile data_etc_message_stage_labyrinth_n_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_labyrinth_n_msg_j_mes[1];
char data_etc_message_stage_labyrinth_w_msg_e_mes__name[45];
fsFile data_etc_message_stage_labyrinth_w_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_labyrinth_w_msg_e_mes[1];
char data_etc_message_stage_labyrinth_w_msg_j_mes__name[45];
fsFile data_etc_message_stage_labyrinth_w_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_labyrinth_w_msg_j_mes[1];
char data_etc_message_stage_lake_msg_e_mes__name[38];
fsFile data_etc_message_stage_lake_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_lake_msg_e_mes[1];
char data_etc_message_stage_lake_msg_j_mes__name[38];
fsFile data_etc_message_stage_lake_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_lake_msg_j_mes[1];
char data_etc_message_stage_observation_msg_e_mes__name[45];
fsFile data_etc_message_stage_observation_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_observation_msg_e_mes[1];
char data_etc_message_stage_observation_msg_j_mes__name[45];
fsFile data_etc_message_stage_observation_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_observation_msg_j_mes[1];
char data_etc_message_stage_prison_bf_msg_e_mes__name[43];
fsFile data_etc_message_stage_prison_bf_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_prison_bf_msg_e_mes[1];
char data_etc_message_stage_prison_bf_msg_j_mes__name[43];
fsFile data_etc_message_stage_prison_bf_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_prison_bf_msg_j_mes[1];
char data_etc_message_stage_prison_n_msg_e_mes__name[42];
fsFile data_etc_message_stage_prison_n_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_prison_n_msg_e_mes[1];
char data_etc_message_stage_prison_n_msg_j_mes__name[42];
fsFile data_etc_message_stage_prison_n_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_prison_n_msg_j_mes[1];
char data_etc_message_stage_prison_s_msg_e_mes__name[42];
fsFile data_etc_message_stage_prison_s_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_prison_s_msg_e_mes[1];
char data_etc_message_stage_prison_s_msg_j_mes__name[42];
fsFile data_etc_message_stage_prison_s_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_prison_s_msg_j_mes[1];
char data_etc_message_stage_sample_msg_e_mes__name[40];
fsFile data_etc_message_stage_sample_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_sample_msg_e_mes[1];
char data_etc_message_stage_sample_msg_j_mes__name[40];
fsFile data_etc_message_stage_sample_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_sample_msg_j_mes[1];
char data_etc_message_stage_society_msg_e_mes__name[41];
fsFile data_etc_message_stage_society_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_society_msg_e_mes[1];
char data_etc_message_stage_society_msg_j_mes__name[41];
fsFile data_etc_message_stage_society_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_society_msg_j_mes[1];
char data_etc_message_stage_tgs_trial_msg_e_mes__name[43];
fsFile data_etc_message_stage_tgs_trial_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_tgs_trial_msg_e_mes[1];
char data_etc_message_stage_tgs_trial_msg_j_mes__name[43];
fsFile data_etc_message_stage_tgs_trial_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_tgs_trial_msg_j_mes[1];
char data_etc_message_stage_to_heaven_msg_e_mes__name[43];
fsFile data_etc_message_stage_to_heaven_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_to_heaven_msg_e_mes[1];
char data_etc_message_stage_to_heaven_msg_j_mes__name[43];
fsFile data_etc_message_stage_to_heaven_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_to_heaven_msg_j_mes[1];
char data_etc_message_stage_toilet_msg_e_mes__name[40];
fsFile data_etc_message_stage_toilet_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_toilet_msg_e_mes[1];
char data_etc_message_stage_toilet_msg_j_mes__name[40];
fsFile data_etc_message_stage_toilet_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_toilet_msg_j_mes[1];
char data_etc_message_stage_town_east_msg_e_mes__name[43];
fsFile data_etc_message_stage_town_east_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_town_east_msg_e_mes[1];
char data_etc_message_stage_town_east_msg_j_mes__name[43];
fsFile data_etc_message_stage_town_east_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_town_east_msg_j_mes[1];
char data_etc_message_stage_town_west_msg_e_mes__name[43];
fsFile data_etc_message_stage_town_west_msg_e_mes__info[1];
fsFileIndex data_etc_message_stage_town_west_msg_e_mes[1];
char data_etc_message_stage_town_west_msg_j_mes__name[43];
fsFile data_etc_message_stage_town_west_msg_j_mes__info[1];
fsFileIndex data_etc_message_stage_town_west_msg_j_mes[1];


