typedef union fsFile;
typedef struct fsCdFile;
typedef struct fsMgcFile;
typedef struct fsMgfFile;
typedef struct fsHdFile;
typedef struct fsMgpFile;
typedef struct _anon0;
typedef union fsFileIndex;
typedef struct _anon1;


typedef fsFileIndex type_0[1];
typedef char type_1[28];
typedef fsFile type_2[1];
typedef char type_3[29];
typedef char type_4[29];
typedef char type_5[26];
typedef fsFileIndex type_6[1];
typedef char type_7[24];
typedef fsFile type_8[1];
typedef fsFile type_9[1];
typedef fsFile type_10[1];
typedef fsFileIndex type_11[1];
typedef fsFile type_12[1];
typedef fsFile type_13[1];
typedef fsFileIndex type_14[1];
typedef char type_15[29];
typedef fsFile type_16[1];
typedef fsFile type_17[1];
typedef char type_18[32];
typedef fsFileIndex type_19[1];
typedef fsFileIndex type_20[1];
typedef fsFileIndex type_21[1];
typedef char type_22[26];
typedef char type_23[26];
typedef char type_24[29];
typedef fsFileIndex type_25[1];
typedef fsFile type_26[1];
typedef char type_27[24];
typedef char type_28[25];
typedef char type_29[29];
typedef fsFile type_30[1];
typedef fsFile type_31[1];
typedef fsFileIndex type_32[1];
typedef fsFile type_33[1];
typedef fsFile type_34[1];
typedef fsFileIndex type_35[1];
typedef fsFile type_36[1];
typedef fsFileIndex type_37[1];
typedef fsFile type_38[1];
typedef fsFile type_39[1];
typedef fsFileIndex type_40[1];
typedef char type_41[33];
typedef char type_42[26];
typedef char type_43[24];
typedef fsFileIndex type_44[1];
typedef fsFile type_45[1];
typedef fsFileIndex type_46[1];
typedef fsFileIndex type_47[1];
typedef fsFile type_48[1];
typedef fsFileIndex type_49[1];
typedef char type_50[28];
typedef char type_51[24];
typedef fsFileIndex type_52[1];
typedef fsFileIndex type_53[1];
typedef char type_54[28];
typedef char type_55[26];
typedef char type_56[28];
typedef char type_57[28];
typedef char type_58[30];
typedef fsFile type_59[1];
typedef char type_60[28];
typedef fsFileIndex type_61[1];
typedef fsFile type_62[1];
typedef char type_63[28];
typedef fsFile type_64[1];
typedef fsFile type_65[1];
typedef fsFileIndex type_66[1];
typedef fsFile type_67[1];
typedef fsFile type_68[1];
typedef char type_69[29];
typedef fsFileIndex type_70[1];
typedef char type_71[24];
typedef fsFile type_72[1];
typedef fsFileIndex type_73[1];
typedef fsFileIndex type_74[1];
typedef fsFileIndex type_75[1];
typedef fsFileIndex type_76[1];
typedef fsFileIndex type_77[1];
typedef fsFile type_78[1];
typedef fsFileIndex type_79[1];
typedef char type_80[27];
typedef fsFile type_81[1];
typedef char type_82[30];
typedef char type_83[28];
typedef char type_84[31];
typedef fsFileIndex type_85[1];
typedef char type_86[24];
typedef fsFile type_87[1];
typedef fsFile type_88[1];
typedef char type_89[25];
typedef fsFile type_90[1];
typedef fsFileIndex type_91[1];
typedef fsFile type_92[1];
typedef fsFile type_93[1];
typedef fsFile type_94[1];
typedef fsFile type_95[1];
typedef fsFile type_96[1];
typedef char type_97[27];
typedef fsFileIndex type_98[1];
typedef char type_99[26];
typedef char type_100[27];
typedef fsFileIndex type_101[1];
typedef fsFileIndex type_102[1];
typedef fsFileIndex type_103[1];
typedef char type_104[29];
typedef char type_105[22];
typedef char type_106[29];
typedef fsFileIndex type_107[1];
typedef fsFile type_108[1];
typedef char type_109[28];
typedef char type_110[28];
typedef fsFile type_111[1];
typedef fsFileIndex type_112[1];
typedef char type_113[22];
typedef fsFileIndex type_114[1];
typedef fsFile type_115[1];
typedef fsFile type_116[1];
typedef fsFile type_117[1];
typedef fsFileIndex type_118[1];
typedef fsFile type_119[1];
typedef fsFile type_120[1];
typedef char type_121[30];
typedef char type_122[24];
typedef fsFile type_123[1];
typedef fsFileIndex type_124[1];
typedef fsFileIndex type_125[1];
typedef char type_126[27];
typedef char type_127[24];
typedef fsFileIndex type_128[1];
typedef char type_129[26];
typedef fsFileIndex type_130[1];
typedef fsFileIndex type_131[1];
typedef char type_132[26];
typedef char type_133[27];
typedef char type_134[26];
typedef char type_135[29];
typedef fsFile type_136[1];
typedef char type_137[27];
typedef fsFileIndex type_138[1];
typedef fsFileIndex type_139[1];
typedef fsFile type_140[1];
typedef char type_141[30];
typedef fsFile type_142[1];
typedef fsFile type_143[1];
typedef fsFile type_144[1];
typedef fsFile type_145[1];
typedef fsFileIndex type_146[1];
typedef fsFile type_147[1];
typedef fsFile type_148[1];
typedef char type_149[25];
typedef fsFileIndex type_150[1];
typedef fsFileIndex type_151[1];
typedef char type_152[24];
typedef fsFileIndex type_153[1];
typedef fsFileIndex type_154[1];
typedef fsFileIndex type_155[1];
typedef fsFileIndex type_156[1];
typedef fsFileIndex type_157[1];
typedef char type_158[28];
typedef fsFile type_159[1];
typedef char type_160[28];
typedef char type_161[28];
typedef fsFile type_162[1];
typedef char type_163[29];
typedef fsFile type_164[1];
typedef fsFileIndex type_165[1];
typedef char type_166[24];
typedef fsFile type_167[1];
typedef fsFile type_168[1];
typedef char type_169[28];
typedef fsFile type_170[1];
typedef fsFile type_171[1];
typedef fsFile type_172[1];
typedef fsFile type_173[1];
typedef fsFile type_174[1];
typedef fsFile type_175[1];
typedef fsFileIndex type_176[1];
typedef char type_177[28];
typedef fsFileIndex type_178[1];
typedef fsFile type_179[1];
typedef fsFileIndex type_180[1];
typedef fsFileIndex type_181[1];
typedef char type_182[28];
typedef char type_183[25];
typedef fsFileIndex type_184[1];
typedef fsFileIndex type_185[1];
typedef fsFile type_186[1];
typedef char type_187[28];
typedef char type_188[32];
typedef char type_189[27];
typedef fsFile type_190[1];
typedef fsFileIndex type_191[1];
typedef char type_192[27];
typedef char type_193[22];
typedef fsFileIndex type_194[1];
typedef fsFile type_195[1];
typedef fsFile type_196[1];
typedef fsFileIndex type_197[1];
typedef fsFile type_198[1];
typedef fsFile type_199[1];
typedef char type_200[24];
typedef fsFileIndex type_201[1];
typedef char type_202[24];
typedef char type_203[25];
typedef fsFile type_204[1];
typedef fsFileIndex type_205[1];
typedef fsFileIndex type_206[1];
typedef fsFile type_207[1];
typedef char type_208[22];
typedef char type_209[28];
typedef fsFileIndex type_210[1];
typedef fsFileIndex type_211[1];
typedef fsFileIndex type_212[1];
typedef fsFileIndex type_213[1];
typedef fsFileIndex type_214[1];
typedef fsFile type_215[1];
typedef fsFileIndex type_216[1];
typedef char type_217[26];
typedef char type_218[29];
typedef fsFile type_219[1];
typedef char type_220[30];
typedef fsFile type_221[1];
typedef char type_222[24];
typedef fsFile type_223[1];
typedef fsFile type_224[1];
typedef fsFile type_225[1];
typedef char type_226[18];
typedef fsFileIndex type_227[1];
typedef fsFile type_228[1];
typedef fsFile type_229[1];
typedef char type_230[28];
typedef fsFileIndex type_231[1];
typedef char type_232[24];
typedef fsFile type_233[1];
typedef char type_234[27];
typedef fsFileIndex type_235[1];
typedef fsFileIndex type_236[1];
typedef fsFileIndex type_237[1];
typedef fsFileIndex type_238[1];
typedef char type_239[30];
typedef char type_240[27];
typedef fsFile type_241[1];
typedef fsFileIndex type_242[1];
typedef char type_243[28];
typedef char type_244[31];
typedef fsFile type_245[1];
typedef fsFileIndex type_246[1];
typedef char type_247[24];
typedef fsFile type_248[1];
typedef fsFile type_249[1];
typedef fsFile type_250[1];
typedef fsFile type_251[1];
typedef fsFile type_252[1];
typedef fsFile type_253[1];
typedef char type_254[31];
typedef fsFileIndex type_255[1];
typedef char type_256[27];
typedef fsFileIndex type_257[1];
typedef fsFile type_258[1];
typedef fsFileIndex type_259[1];
typedef fsFileIndex type_260[1];
typedef fsFileIndex type_261[1];
typedef char type_262[28];
typedef char type_263[28];
typedef fsFileIndex type_264[1];
typedef fsFileIndex type_265[1];
typedef fsFileIndex type_266[1];
typedef fsFile type_267[1];
typedef char type_268[26];
typedef char type_269[24];
typedef fsFile type_270[1];
typedef char type_271[29];
typedef fsFile type_272[1];
typedef fsFile type_273[1];
typedef fsFileIndex type_274[1];
typedef fsFile type_275[1];
typedef fsFileIndex type_276[1];
typedef fsFile type_277[1];
typedef char type_278[26];
typedef fsFileIndex type_279[1];
typedef char type_280[24];
typedef fsFile type_281[1];
typedef fsFileIndex type_282[1];
typedef fsFileIndex type_283[1];
typedef fsFile type_284[1];
typedef fsFileIndex type_285[1];
typedef fsFileIndex type_286[1];
typedef fsFileIndex type_287[1];
typedef fsFileIndex type_288[1];
typedef char type_289[32];
typedef fsFileIndex type_290[1];

union fsFile
{
	_anon0 check;
	<unknown fundamental type (0xa510)> pack;
	fsCdFile cd;
	fsHdFile hd;
	fsMgcFile mgc;
	fsMgfFile mgf;
	fsMgpFile mgp;
};

struct fsCdFile
{
	struct
	{
		int type : 8;
		int number : 24;
	};
	char* name;
	int lsn;
	int size;
};

struct fsMgcFile
{
	struct
	{
		int type : 8;
		int padding : 24;
	};
	fsFile* parent;
	char* start;
	char* end;
};

struct fsMgfFile
{
	struct
	{
		int type : 8;
		int padding : 24;
	};
	fsFile* parent;
	int offset;
	int size;
};

struct fsHdFile
{
	struct
	{
		int type : 8;
		int padding : 24;
	};
	char* name;
	int offset;
	int size;
};

struct fsMgpFile
{
	struct
	{
		int type : 8;
		int padding : 24;
	};
	fsFile* file;
	fsMgcFile* start;
	fsMgcFile* end;
};

struct _anon0
{
	struct
	{
		int type : 8;
		int number : 24;
	};
	int pad0;
	int pad1;
	int pad2;
};

union fsFileIndex
{
	_anon1 index;
	unsigned long pack;
};

struct _anon1
{
	fsFile* fp;
	char* name;
};

char data_chr_item_mgf__name[18];
fsFile data_chr_item_mgf__info[1];
fsFileIndex data_chr_item_mgf[1];
char data_chr_item_b_ami_mdl__name[24];
fsFile data_chr_item_b_ami_mdl__info[1];
fsFileIndex data_chr_item_b_ami_mdl[1];
char data_chr_item_b_clo_mdl__name[24];
fsFile data_chr_item_b_clo_mdl__info[1];
fsFileIndex data_chr_item_b_clo_mdl[1];
char data_chr_item_b_d00_mdl__name[24];
fsFile data_chr_item_b_d00_mdl__info[1];
fsFileIndex data_chr_item_b_d00_mdl[1];
char data_chr_item_b_d01_mdl__name[24];
fsFile data_chr_item_b_d01_mdl__info[1];
fsFileIndex data_chr_item_b_d01_mdl[1];
char data_chr_item_b_d02_mdl__name[24];
fsFile data_chr_item_b_d02_mdl__info[1];
fsFileIndex data_chr_item_b_d02_mdl[1];
char data_chr_item_b_d03_mdl__name[24];
fsFile data_chr_item_b_d03_mdl__info[1];
fsFileIndex data_chr_item_b_d03_mdl[1];
char data_chr_item_b_d05_mdl__name[24];
fsFile data_chr_item_b_d05_mdl__info[1];
fsFileIndex data_chr_item_b_d05_mdl[1];
char data_chr_item_b_doo_mdl__name[24];
fsFile data_chr_item_b_doo_mdl__info[1];
fsFileIndex data_chr_item_b_doo_mdl[1];
char data_chr_item_b_nik_anm__name[24];
fsFile data_chr_item_b_nik_anm__info[1];
fsFileIndex data_chr_item_b_nik_anm[1];
char data_chr_item_b_nik_mdl__name[24];
fsFile data_chr_item_b_nik_mdl__info[1];
fsFileIndex data_chr_item_b_nik_mdl[1];
char data_chr_item_b_pia_mdl__name[24];
fsFile data_chr_item_b_pia_mdl__info[1];
fsFileIndex data_chr_item_b_pia_mdl[1];
char data_chr_item_b_rei_kg1__name[24];
fsFile data_chr_item_b_rei_kg1__info[1];
fsFileIndex data_chr_item_b_rei_kg1[1];
char data_chr_item_b_rei_mdl__name[24];
fsFile data_chr_item_b_rei_mdl__info[1];
fsFileIndex data_chr_item_b_rei_mdl[1];
char data_chr_item_b_rop_mdl__name[24];
fsFile data_chr_item_b_rop_mdl__info[1];
fsFileIndex data_chr_item_b_rop_mdl[1];
char data_chr_item_b_tel_mdl__name[24];
fsFile data_chr_item_b_tel_mdl__info[1];
fsFileIndex data_chr_item_b_tel_mdl[1];
char data_chr_item_box_mdl__name[22];
fsFile data_chr_item_box_mdl__info[1];
fsFileIndex data_chr_item_box_mdl[1];
char data_chr_item_c1b_mdl__name[22];
fsFile data_chr_item_c1b_mdl__info[1];
fsFileIndex data_chr_item_c1b_mdl[1];
char data_chr_item_g_drink_mdl__name[26];
fsFile data_chr_item_g_drink_mdl__info[1];
fsFileIndex data_chr_item_g_drink_mdl[1];
char data_chr_item_g_firstaid_mdl__name[29];
fsFile data_chr_item_g_firstaid_mdl__info[1];
fsFileIndex data_chr_item_g_firstaid_mdl[1];
char data_chr_item_g_hair_mdl__name[25];
fsFile data_chr_item_g_hair_mdl__info[1];
fsFileIndex data_chr_item_g_hair_mdl[1];
char data_chr_item_g_handbul_mdl__name[28];
fsFile data_chr_item_g_handbul_mdl__info[1];
fsFileIndex data_chr_item_g_handbul_mdl[1];
char data_chr_item_g_handgun_mdl__name[28];
fsFile data_chr_item_g_handgun_mdl__info[1];
fsFileIndex data_chr_item_g_handgun_mdl[1];
char data_chr_item_g_jlight_mdl__name[27];
fsFile data_chr_item_g_jlight_mdl__info[1];
fsFileIndex data_chr_item_g_jlight_mdl[1];
char data_chr_item_g_kakuzai_mdl__name[28];
fsFile data_chr_item_g_kakuzai_mdl__info[1];
fsFileIndex data_chr_item_g_kakuzai_mdl[1];
char data_chr_item_g_keyelevator_mdl__name[32];
fsFile data_chr_item_g_keyelevator_mdl__info[1];
fsFileIndex data_chr_item_g_keyelevator_mdl[1];
char data_chr_item_g_keypurple_mdl__name[30];
fsFile data_chr_item_g_keypurple_mdl__info[1];
fsFileIndex data_chr_item_g_keypurple_mdl[1];
char data_chr_item_g_letterm_mdl__name[28];
fsFile data_chr_item_g_letterm_mdl__info[1];
fsFileIndex data_chr_item_g_letterm_mdl[1];
char data_chr_item_g_needle_mdl__name[27];
fsFile data_chr_item_g_needle_mdl__info[1];
fsFileIndex data_chr_item_g_needle_mdl[1];
char data_chr_item_g_radio_mdl__name[26];
fsFile data_chr_item_g_radio_mdl__info[1];
fsFileIndex data_chr_item_g_radio_mdl[1];
char data_chr_item_gom_mdl__name[22];
fsFile data_chr_item_gom_mdl__info[1];
fsFileIndex data_chr_item_gom_mdl[1];
char data_chr_item_i_bear_mdl__name[25];
fsFile data_chr_item_i_bear_mdl__info[1];
fsFileIndex data_chr_item_i_bear_mdl[1];
char data_chr_item_i_bear2_mdl__name[26];
fsFile data_chr_item_i_bear2_mdl__info[1];
fsFileIndex data_chr_item_i_bear2_mdl[1];
char data_chr_item_i_flight_mdl__name[27];
fsFile data_chr_item_i_flight_mdl__info[1];
fsFileIndex data_chr_item_i_flight_mdl[1];
char data_chr_item_i_handgun_mdl__name[28];
fsFile data_chr_item_i_handgun_mdl__info[1];
fsFileIndex data_chr_item_i_handgun_mdl[1];
char data_chr_item_i_j_light_mdl__name[28];
fsFile data_chr_item_i_j_light_mdl__info[1];
fsFileIndex data_chr_item_i_j_light_mdl[1];
char data_chr_item_i_kakuzai_mdl__name[28];
fsFile data_chr_item_i_kakuzai_mdl__info[1];
fsFileIndex data_chr_item_i_kakuzai_mdl[1];
char data_chr_item_i_key_clock_mdl__name[30];
fsFile data_chr_item_i_key_clock_mdl__info[1];
fsFileIndex data_chr_item_i_key_clock_mdl[1];
char data_chr_item_i_keycou_mdl__name[27];
fsFile data_chr_item_i_keycou_mdl__info[1];
fsFileIndex data_chr_item_i_keycou_mdl[1];
char data_chr_item_i_keyelevator_mdl__name[32];
fsFile data_chr_item_i_keyelevator_mdl__info[1];
fsFileIndex data_chr_item_i_keyelevator_mdl[1];
char data_chr_item_i_keyspe_mdl__name[27];
fsFile data_chr_item_i_keyspe_mdl__info[1];
fsFileIndex data_chr_item_i_keyspe_mdl[1];
char data_chr_item_i_letter_mdl__name[27];
fsFile data_chr_item_i_letter_mdl__info[1];
fsFileIndex data_chr_item_i_letter_mdl[1];
char data_chr_item_i_magazine_mdl__name[29];
fsFile data_chr_item_i_magazine_mdl__info[1];
fsFileIndex data_chr_item_i_magazine_mdl[1];
char data_chr_item_i_mdrug_mdl__name[26];
fsFile data_chr_item_i_mdrug_mdl__info[1];
fsFileIndex data_chr_item_i_mdrug_mdl[1];
char data_chr_item_i_mtablet_mdl__name[28];
fsFile data_chr_item_i_mtablet_mdl__info[1];
fsFileIndex data_chr_item_i_mtablet_mdl[1];
char data_chr_item_i_needle_mdl__name[27];
fsFile data_chr_item_i_needle_mdl__info[1];
fsFileIndex data_chr_item_i_needle_mdl[1];
char data_chr_item_i_purse_mdl__name[26];
fsFile data_chr_item_i_purse_mdl__info[1];
fsFileIndex data_chr_item_i_purse_mdl[1];
char data_chr_item_i_radio_mdl__name[26];
fsFile data_chr_item_i_radio_mdl__info[1];
fsFileIndex data_chr_item_i_radio_mdl[1];
char data_chr_item_mne_mdl__name[22];
fsFile data_chr_item_mne_mdl__info[1];
fsFileIndex data_chr_item_mne_mdl[1];
char data_chr_item_x_bear_mdl__name[25];
fsFile data_chr_item_x_bear_mdl__info[1];
fsFileIndex data_chr_item_x_bear_mdl[1];
char data_chr_item_x_canopen_mdl__name[28];
fsFile data_chr_item_x_canopen_mdl__info[1];
fsFileIndex data_chr_item_x_canopen_mdl[1];
char data_chr_item_x_cinderella_mdl__name[31];
fsFile data_chr_item_x_cinderella_mdl__info[1];
fsFileIndex data_chr_item_x_cinderella_mdl[1];
char data_chr_item_x_coinprisoner_mdl__name[33];
fsFile data_chr_item_x_coinprisoner_mdl__info[1];
fsFileIndex data_chr_item_x_coinprisoner_mdl[1];
char data_chr_item_x_coinsnake_mdl__name[30];
fsFile data_chr_item_x_coinsnake_mdl__info[1];
fsFileIndex data_chr_item_x_coinsnake_mdl[1];
char data_chr_item_x_cup_mdl__name[24];
fsFile data_chr_item_x_cup_mdl__info[1];
fsFileIndex data_chr_item_x_cup_mdl[1];
char data_chr_item_x_drink_mdl__name[26];
fsFile data_chr_item_x_drink_mdl__info[1];
fsFileIndex data_chr_item_x_drink_mdl[1];
char data_chr_item_x_firstaid_mdl__name[29];
fsFile data_chr_item_x_firstaid_mdl__info[1];
fsFileIndex data_chr_item_x_firstaid_mdl[1];
char data_chr_item_x_hair_mdl__name[25];
fsFile data_chr_item_x_hair_mdl__info[1];
fsFileIndex data_chr_item_x_hair_mdl[1];
char data_chr_item_x_handbul_mdl__name[28];
fsFile data_chr_item_x_handbul_mdl__info[1];
fsFileIndex data_chr_item_x_handbul_mdl[1];
char data_chr_item_x_handgun_mdl__name[28];
fsFile data_chr_item_x_handgun_mdl__info[1];
fsFileIndex data_chr_item_x_handgun_mdl[1];
char data_chr_item_x_jlight_mdl__name[27];
fsFile data_chr_item_x_jlight_mdl__info[1];
fsFileIndex data_chr_item_x_jlight_mdl[1];
char data_chr_item_x_juice_mdl__name[26];
fsFile data_chr_item_x_juice_mdl__info[1];
fsFileIndex data_chr_item_x_juice_mdl[1];
char data_chr_item_x_kakuzai_mdl__name[28];
fsFile data_chr_item_x_kakuzai_mdl__info[1];
fsFileIndex data_chr_item_x_kakuzai_mdl[1];
char data_chr_item_x_key202_mdl__name[27];
fsFile data_chr_item_x_key202_mdl__info[1];
fsFileIndex data_chr_item_x_key202_mdl[1];
char data_chr_item_x_keybase_mdl__name[28];
fsFile data_chr_item_x_keybase_mdl__info[1];
fsFileIndex data_chr_item_x_keybase_mdl[1];
char data_chr_item_x_keybronze_mdl__name[30];
fsFile data_chr_item_x_keybronze_mdl__info[1];
fsFileIndex data_chr_item_x_keybronze_mdl[1];
char data_chr_item_x_keyclock_mdl__name[29];
fsFile data_chr_item_x_keyclock_mdl__info[1];
fsFileIndex data_chr_item_x_keyclock_mdl[1];
char data_chr_item_x_keycourt_mdl__name[29];
fsFile data_chr_item_x_keycourt_mdl__info[1];
fsFileIndex data_chr_item_x_keycourt_mdl[1];
char data_chr_item_x_keyelevator_mdl__name[32];
fsFile data_chr_item_x_keyelevator_mdl__info[1];
fsFileIndex data_chr_item_x_keyelevator_mdl[1];
char data_chr_item_x_keyemerg_mdl__name[29];
fsFile data_chr_item_x_keyemerg_mdl__info[1];
fsFileIndex data_chr_item_x_keyemerg_mdl[1];
char data_chr_item_x_keygate_mdl__name[28];
fsFile data_chr_item_x_keygate_mdl__info[1];
fsFileIndex data_chr_item_x_keygate_mdl[1];
char data_chr_item_x_keyhos_mdl__name[27];
fsFile data_chr_item_x_keyhos_mdl__info[1];
fsFileIndex data_chr_item_x_keyhos_mdl[1];
char data_chr_item_x_keylyne_mdl__name[28];
fsFile data_chr_item_x_keylyne_mdl__info[1];
fsFileIndex data_chr_item_x_keylyne_mdl[1];
char data_chr_item_x_keynorth_mdl__name[29];
fsFile data_chr_item_x_keynorth_mdl__info[1];
fsFileIndex data_chr_item_x_keynorth_mdl[1];
char data_chr_item_x_keypurple_mdl__name[30];
fsFile data_chr_item_x_keypurple_mdl__info[1];
fsFileIndex data_chr_item_x_keypurple_mdl[1];
char data_chr_item_x_keyrapis_mdl__name[29];
fsFile data_chr_item_x_keyrapis_mdl__info[1];
fsFileIndex data_chr_item_x_keyrapis_mdl[1];
char data_chr_item_x_keyroof_mdl__name[28];
fsFile data_chr_item_x_keyroof_mdl__info[1];
fsFileIndex data_chr_item_x_keyroof_mdl[1];
char data_chr_item_x_letterm_mdl__name[28];
fsFile data_chr_item_x_letterm_mdl__info[1];
fsFileIndex data_chr_item_x_letterm_mdl[1];
char data_chr_item_x_lostmemory_mdl__name[31];
fsFile data_chr_item_x_lostmemory_mdl__info[1];
fsFileIndex data_chr_item_x_lostmemory_mdl[1];
char data_chr_item_x_magazine_mdl__name[29];
fsFile data_chr_item_x_magazine_mdl__info[1];
fsFileIndex data_chr_item_x_magazine_mdl[1];
char data_chr_item_x_mermaid_mdl__name[28];
fsFile data_chr_item_x_mermaid_mdl__info[1];
fsFileIndex data_chr_item_x_mermaid_mdl[1];
char data_chr_item_x_needle_mdl__name[27];
fsFile data_chr_item_x_needle_mdl__info[1];
fsFileIndex data_chr_item_x_needle_mdl[1];
char data_chr_item_x_oil_mdl__name[24];
fsFile data_chr_item_x_oil_mdl__info[1];
fsFileIndex data_chr_item_x_oil_mdl[1];
char data_chr_item_x_pictstand_mdl__name[30];
fsFile data_chr_item_x_pictstand_mdl__info[1];
fsFileIndex data_chr_item_x_pictstand_mdl[1];
char data_chr_item_x_plier_mdl__name[26];
fsFile data_chr_item_x_plier_mdl__info[1];
fsFileIndex data_chr_item_x_plier_mdl[1];
char data_chr_item_x_purse_mdl__name[26];
fsFile data_chr_item_x_purse_mdl__info[1];
fsFileIndex data_chr_item_x_purse_mdl[1];
char data_chr_item_x_radio_mdl__name[26];
fsFile data_chr_item_x_radio_mdl__info[1];
fsFileIndex data_chr_item_x_radio_mdl[1];
char data_chr_item_x_redrelig_mdl__name[29];
fsFile data_chr_item_x_redrelig_mdl__info[1];
fsFileIndex data_chr_item_x_redrelig_mdl[1];
char data_chr_item_x_riflebul_mdl__name[29];
fsFile data_chr_item_x_riflebul_mdl__info[1];
fsFileIndex data_chr_item_x_riflebul_mdl[1];
char data_chr_item_x_ringcopper_mdl__name[31];
fsFile data_chr_item_x_ringcopper_mdl__info[1];
fsFileIndex data_chr_item_x_ringcopper_mdl[1];
char data_chr_item_x_ringlead_mdl__name[29];
fsFile data_chr_item_x_ringlead_mdl__info[1];
fsFileIndex data_chr_item_x_ringlead_mdl[1];
char data_chr_item_x_shotbul_mdl__name[28];
fsFile data_chr_item_x_shotbul_mdl__info[1];
fsFileIndex data_chr_item_x_shotbul_mdl[1];
char data_chr_item_x_snow_mdl__name[25];
fsFile data_chr_item_x_snow_mdl__info[1];
fsFileIndex data_chr_item_x_snow_mdl[1];
char data_chr_item_x_spanner_mdl__name[28];
fsFile data_chr_item_x_spanner_mdl__info[1];
fsFileIndex data_chr_item_x_spanner_mdl[1];
char data_chr_item_x_thinner_mdl__name[28];
fsFile data_chr_item_x_thinner_mdl__info[1];
fsFileIndex data_chr_item_x_thinner_mdl[1];
char data_chr_item_x_video_mdl__name[26];
fsFile data_chr_item_x_video_mdl__info[1];
fsFileIndex data_chr_item_x_video_mdl[1];
char data_chr_item_x_waxdoll_mdl__name[28];
fsFile data_chr_item_x_waxdoll_mdl__info[1];
fsFileIndex data_chr_item_x_waxdoll_mdl[1];


