typedef union fsFile;
typedef struct fsCdFile;
typedef struct fsMgcFile;
typedef struct fsMgfFile;
typedef struct fsHdFile;
typedef struct fsMgpFile;
typedef struct _anon0;
typedef union fsFileIndex;
typedef struct _anon1;


typedef fsFileIndex type_0[1];
typedef fsFile type_1[1];
typedef fsFileIndex type_2[1];
typedef char type_3[39];
typedef char type_4[34];
typedef char type_5[35];
typedef char type_6[37];
typedef fsFile type_7[1];
typedef fsFile type_8[1];
typedef fsFile type_9[1];
typedef fsFileIndex type_10[1];
typedef fsFileIndex type_11[1];
typedef fsFileIndex type_12[1];
typedef char type_13[27];
typedef char type_14[31];
typedef char type_15[36];
typedef fsFile type_16[1];
typedef fsFile type_17[1];
typedef fsFileIndex type_18[1];
typedef fsFileIndex type_19[1];
typedef fsFileIndex type_20[1];
typedef char type_21[35];
typedef fsFile type_22[1];
typedef fsFile type_23[1];
typedef fsFileIndex type_24[1];
typedef char type_25[27];
typedef fsFile type_26[1];
typedef fsFileIndex type_27[1];
typedef char type_28[38];
typedef fsFile type_29[1];
typedef char type_30[34];
typedef fsFile type_31[1];
typedef char type_32[37];
typedef fsFile type_33[1];
typedef fsFileIndex type_34[1];
typedef fsFileIndex type_35[1];
typedef fsFileIndex type_36[1];
typedef fsFile type_37[1];
typedef char type_38[27];
typedef char type_39[29];
typedef char type_40[32];
typedef fsFile type_41[1];
typedef fsFile type_42[1];
typedef fsFile type_43[1];
typedef fsFileIndex type_44[1];
typedef fsFileIndex type_45[1];
typedef fsFileIndex type_46[1];
typedef char type_47[34];
typedef char type_48[35];
typedef fsFile type_49[1];
typedef fsFileIndex type_50[1];
typedef fsFileIndex type_51[1];
typedef char type_52[27];
typedef fsFile type_53[1];
typedef fsFile type_54[1];
typedef fsFileIndex type_55[1];
typedef char type_56[35];
typedef fsFile type_57[1];
typedef fsFileIndex type_58[1];
typedef fsFile type_59[1];
typedef fsFileIndex type_60[1];
typedef char type_61[38];
typedef char type_62[33];
typedef char type_63[35];
typedef fsFile type_64[1];
typedef char type_65[36];
typedef fsFile type_66[1];
typedef fsFileIndex type_67[1];
typedef fsFileIndex type_68[1];
typedef fsFileIndex type_69[1];
typedef char type_70[35];
typedef char type_71[34];
typedef char type_72[36];
typedef fsFile type_73[1];
typedef fsFile type_74[1];
typedef fsFileIndex type_75[1];
typedef fsFileIndex type_76[1];
typedef fsFile type_77[1];
typedef fsFileIndex type_78[1];
typedef char type_79[35];
typedef fsFile type_80[1];
typedef fsFileIndex type_81[1];
typedef fsFileIndex type_82[1];
typedef char type_83[27];
typedef fsFile type_84[1];
typedef char type_85[38];
typedef fsFile type_86[1];
typedef char type_87[34];
typedef fsFile type_88[1];
typedef char type_89[38];
typedef fsFileIndex type_90[1];
typedef fsFile type_91[1];
typedef fsFileIndex type_92[1];
typedef fsFileIndex type_93[1];
typedef char type_94[27];
typedef char type_95[34];
typedef char type_96[34];
typedef fsFile type_97[1];
typedef fsFile type_98[1];
typedef fsFile type_99[1];
typedef fsFileIndex type_100[1];
typedef fsFileIndex type_101[1];
typedef char type_102[27];
typedef char type_103[35];
typedef fsFileIndex type_104[1];
typedef fsFile type_105[1];
typedef fsFileIndex type_106[1];
typedef char type_107[27];
typedef fsFile type_108[1];
typedef fsFileIndex type_109[1];
typedef fsFile type_110[1];
typedef fsFileIndex type_111[1];
typedef char type_112[35];
typedef fsFile type_113[1];
typedef fsFileIndex type_114[1];
typedef fsFile type_115[1];
typedef fsFileIndex type_116[1];
typedef char type_117[38];
typedef char type_118[33];
typedef char type_119[34];
typedef fsFile type_120[1];
typedef fsFile type_121[1];
typedef char type_122[27];
typedef fsFile type_123[1];
typedef fsFileIndex type_124[1];
typedef fsFileIndex type_125[1];
typedef fsFileIndex type_126[1];
typedef char type_127[35];
typedef char type_128[34];
typedef char type_129[36];
typedef fsFile type_130[1];
typedef fsFile type_131[1];
typedef fsFileIndex type_132[1];
typedef fsFile type_133[1];
typedef fsFileIndex type_134[1];
typedef fsFileIndex type_135[1];
typedef char type_136[35];
typedef fsFile type_137[1];
typedef fsFileIndex type_138[1];
typedef char type_139[27];
typedef fsFileIndex type_140[1];
typedef fsFile type_141[1];
typedef fsFileIndex type_142[1];
typedef fsFile type_143[1];
typedef char type_144[38];
typedef char type_145[32];
typedef fsFile type_146[1];
typedef char type_147[39];
typedef fsFileIndex type_148[1];
typedef fsFileIndex type_149[1];
typedef fsFile type_150[1];
typedef char type_151[36];
typedef char type_152[34];
typedef char type_153[36];
typedef fsFile type_154[1];
typedef fsFile type_155[1];
typedef fsFile type_156[1];
typedef char type_157[24];
typedef fsFileIndex type_158[1];
typedef fsFileIndex type_159[1];
typedef char type_160[34];
typedef fsFileIndex type_161[1];
typedef char type_162[27];
typedef char type_163[27];
typedef fsFile type_164[1];
typedef fsFileIndex type_165[1];
typedef fsFile type_166[1];
typedef fsFileIndex type_167[1];
typedef fsFileIndex type_168[1];
typedef fsFile type_169[1];
typedef char type_170[35];
typedef fsFile type_171[1];
typedef fsFileIndex type_172[1];
typedef fsFile type_173[1];
typedef fsFileIndex type_174[1];
typedef char type_175[27];
typedef char type_176[38];
typedef fsFile type_177[1];
typedef char type_178[36];
typedef fsFile type_179[1];
typedef char type_180[31];
typedef fsFile type_181[1];
typedef fsFileIndex type_182[1];
typedef fsFileIndex type_183[1];
typedef fsFileIndex type_184[1];
typedef char type_185[35];
typedef char type_186[29];
typedef fsFile type_187[1];
typedef fsFile type_188[1];
typedef fsFileIndex type_189[1];
typedef fsFile type_190[1];
typedef fsFileIndex type_191[1];
typedef fsFileIndex type_192[1];
typedef char type_193[32];
typedef char type_194[35];
typedef fsFile type_195[1];
typedef fsFileIndex type_196[1];
typedef fsFileIndex type_197[1];
typedef fsFile type_198[1];
typedef char type_199[27];
typedef fsFile type_200[1];
typedef char type_201[38];
typedef fsFile type_202[1];
typedef fsFileIndex type_203[1];

union fsFile
{
	_anon0 check;
	<unknown fundamental type (0xa510)> pack;
	fsCdFile cd;
	fsHdFile hd;
	fsMgcFile mgc;
	fsMgfFile mgf;
	fsMgpFile mgp;
};

struct fsCdFile
{
	struct
	{
		int type : 8;
		int number : 24;
	};
	char* name;
	int lsn;
	int size;
};

struct fsMgcFile
{
	struct
	{
		int type : 8;
		int padding : 24;
	};
	fsFile* parent;
	char* start;
	char* end;
};

struct fsMgfFile
{
	struct
	{
		int type : 8;
		int padding : 24;
	};
	fsFile* parent;
	int offset;
	int size;
};

struct fsHdFile
{
	struct
	{
		int type : 8;
		int padding : 24;
	};
	char* name;
	int offset;
	int size;
};

struct fsMgpFile
{
	struct
	{
		int type : 8;
		int padding : 24;
	};
	fsFile* file;
	fsMgcFile* start;
	fsMgcFile* end;
};

struct _anon0
{
	struct
	{
		int type : 8;
		int number : 24;
	};
	int pad0;
	int pad1;
	int pad2;
};

union fsFileIndex
{
	_anon1 index;
	unsigned long pack;
};

struct _anon1
{
	fsFile* fp;
	char* name;
};

char data_sound_snd_data_mgf__name[24];
fsFile data_sound_snd_data_mgf__info[1];
fsFileIndex data_sound_snd_data_mgf[1];
char data_sound_snd_data_ap_sdb__name[27];
fsFile data_sound_snd_data_ap_sdb__info[1];
fsFileIndex data_sound_snd_data_ap_sdb[1];
char data_sound_snd_data_apart_e1f_sdb__name[34];
fsFile data_sound_snd_data_apart_e1f_sdb__info[1];
fsFileIndex data_sound_snd_data_apart_e1f_sdb[1];
char data_sound_snd_data_apart_e2f_sdb__name[34];
fsFile data_sound_snd_data_apart_e2f_sdb__info[1];
fsFileIndex data_sound_snd_data_apart_e2f_sdb[1];
char data_sound_snd_data_apart_e3fe_sdb__name[35];
fsFile data_sound_snd_data_apart_e3fe_sdb__info[1];
fsFileIndex data_sound_snd_data_apart_e3fe_sdb[1];
char data_sound_snd_data_apart_e3fw_sdb__name[35];
fsFile data_sound_snd_data_apart_e3fw_sdb__info[1];
fsFileIndex data_sound_snd_data_apart_e3fw_sdb[1];
char data_sound_snd_data_apart_out_sdb__name[34];
fsFile data_sound_snd_data_apart_out_sdb__info[1];
fsFileIndex data_sound_snd_data_apart_out_sdb[1];
char data_sound_snd_data_apart_stair_sdb__name[36];
fsFile data_sound_snd_data_apart_stair_sdb__info[1];
fsFileIndex data_sound_snd_data_apart_stair_sdb[1];
char data_sound_snd_data_apart_w1f_sdb__name[34];
fsFile data_sound_snd_data_apart_w1f_sdb__info[1];
fsFileIndex data_sound_snd_data_apart_w1f_sdb[1];
char data_sound_snd_data_apart_w2f_sdb__name[34];
fsFile data_sound_snd_data_apart_w2f_sdb__info[1];
fsFileIndex data_sound_snd_data_apart_w2f_sdb[1];
char data_sound_snd_data_bowling_sdb__name[32];
fsFile data_sound_snd_data_bowling_sdb__info[1];
fsFileIndex data_sound_snd_data_bowling_sdb[1];
char data_sound_snd_data_bw_sdb__name[27];
fsFile data_sound_snd_data_bw_sdb__info[1];
fsFileIndex data_sound_snd_data_bw_sdb[1];
char data_sound_snd_data_ca_sdb__name[27];
fsFile data_sound_snd_data_ca_sdb__info[1];
fsFileIndex data_sound_snd_data_ca_sdb[1];
char data_sound_snd_data_cb_sdb__name[27];
fsFile data_sound_snd_data_cb_sdb__info[1];
fsFileIndex data_sound_snd_data_cb_sdb[1];
char data_sound_snd_data_cc_sdb__name[27];
fsFile data_sound_snd_data_cc_sdb__info[1];
fsFileIndex data_sound_snd_data_cc_sdb[1];
char data_sound_snd_data_cd_sdb__name[27];
fsFile data_sound_snd_data_cd_sdb__info[1];
fsFileIndex data_sound_snd_data_cd_sdb[1];
char data_sound_snd_data_delusion_2_sdb__name[35];
fsFile data_sound_snd_data_delusion_2_sdb__info[1];
fsFileIndex data_sound_snd_data_delusion_2_sdb[1];
char data_sound_snd_data_delusion_3_sdb__name[35];
fsFile data_sound_snd_data_delusion_3_sdb__info[1];
fsFileIndex data_sound_snd_data_delusion_3_sdb[1];
char data_sound_snd_data_eddie_boss_sdb__name[35];
fsFile data_sound_snd_data_eddie_boss_sdb__info[1];
fsFileIndex data_sound_snd_data_eddie_boss_sdb[1];
char data_sound_snd_data_end_dog_sdb__name[32];
fsFile data_sound_snd_data_end_dog_sdb__info[1];
fsFileIndex data_sound_snd_data_end_dog_sdb[1];
char data_sound_snd_data_end_maria_sdb__name[34];
fsFile data_sound_snd_data_end_maria_sdb__info[1];
fsFileIndex data_sound_snd_data_end_maria_sdb[1];
char data_sound_snd_data_end_rebirth_sdb__name[36];
fsFile data_sound_snd_data_end_rebirth_sdb__info[1];
fsFileIndex data_sound_snd_data_end_rebirth_sdb[1];
char data_sound_snd_data_end_recovery_sdb__name[37];
fsFile data_sound_snd_data_end_recovery_sdb__info[1];
fsFileIndex data_sound_snd_data_end_recovery_sdb[1];
char data_sound_snd_data_end_suicide_sdb__name[36];
fsFile data_sound_snd_data_end_suicide_sdb__info[1];
fsFileIndex data_sound_snd_data_end_suicide_sdb[1];
char data_sound_snd_data_er_sdb__name[27];
fsFile data_sound_snd_data_er_sdb__info[1];
fsFileIndex data_sound_snd_data_er_sdb[1];
char data_sound_snd_data_forest_sdb__name[31];
fsFile data_sound_snd_data_forest_sdb__info[1];
fsFileIndex data_sound_snd_data_forest_sdb[1];
char data_sound_snd_data_heaven_night_sdb__name[37];
fsFile data_sound_snd_data_heaven_night_sdb__info[1];
fsFileIndex data_sound_snd_data_heaven_night_sdb[1];
char data_sound_snd_data_hospital_1f_f_sdb__name[38];
fsFile data_sound_snd_data_hospital_1f_f_sdb__info[1];
fsFileIndex data_sound_snd_data_hospital_1f_f_sdb[1];
char data_sound_snd_data_hospital_1fe_b_sdb__name[39];
fsFile data_sound_snd_data_hospital_1fe_b_sdb__info[1];
fsFileIndex data_sound_snd_data_hospital_1fe_b_sdb[1];
char data_sound_snd_data_hospital_1fw_b_sdb__name[39];
fsFile data_sound_snd_data_hospital_1fw_b_sdb__info[1];
fsFileIndex data_sound_snd_data_hospital_1fw_b_sdb[1];
char data_sound_snd_data_hospital_2f_b_sdb__name[38];
fsFile data_sound_snd_data_hospital_2f_b_sdb__info[1];
fsFileIndex data_sound_snd_data_hospital_2f_b_sdb[1];
char data_sound_snd_data_hospital_2f_f_sdb__name[38];
fsFile data_sound_snd_data_hospital_2f_f_sdb__info[1];
fsFileIndex data_sound_snd_data_hospital_2f_f_sdb[1];
char data_sound_snd_data_hospital_3f_b_sdb__name[38];
fsFile data_sound_snd_data_hospital_3f_b_sdb__info[1];
fsFileIndex data_sound_snd_data_hospital_3f_b_sdb[1];
char data_sound_snd_data_hospital_3f_f_sdb__name[38];
fsFile data_sound_snd_data_hospital_3f_f_sdb__info[1];
fsFileIndex data_sound_snd_data_hospital_3f_f_sdb[1];
char data_sound_snd_data_hospital_bf_b_sdb__name[38];
fsFile data_sound_snd_data_hospital_bf_b_sdb__info[1];
fsFileIndex data_sound_snd_data_hospital_bf_b_sdb[1];
char data_sound_snd_data_hospital_pass_sdb__name[38];
fsFile data_sound_snd_data_hospital_pass_sdb__info[1];
fsFileIndex data_sound_snd_data_hospital_pass_sdb[1];
char data_sound_snd_data_hospital_rf_f_sdb__name[38];
fsFile data_sound_snd_data_hospital_rf_f_sdb__info[1];
fsFileIndex data_sound_snd_data_hospital_rf_f_sdb[1];
char data_sound_snd_data_hotel_1f_b_sdb__name[35];
fsFile data_sound_snd_data_hotel_1f_b_sdb__info[1];
fsFileIndex data_sound_snd_data_hotel_1f_b_sdb[1];
char data_sound_snd_data_hotel_1f_f_sdb__name[35];
fsFile data_sound_snd_data_hotel_1f_f_sdb__info[1];
fsFileIndex data_sound_snd_data_hotel_1f_f_sdb[1];
char data_sound_snd_data_hotel_2f_b_sdb__name[35];
fsFile data_sound_snd_data_hotel_2f_b_sdb__info[1];
fsFileIndex data_sound_snd_data_hotel_2f_b_sdb[1];
char data_sound_snd_data_hotel_2f_f_sdb__name[35];
fsFile data_sound_snd_data_hotel_2f_f_sdb__info[1];
fsFileIndex data_sound_snd_data_hotel_2f_f_sdb[1];
char data_sound_snd_data_hotel_3f_b_sdb__name[35];
fsFile data_sound_snd_data_hotel_3f_b_sdb__info[1];
fsFileIndex data_sound_snd_data_hotel_3f_b_sdb[1];
char data_sound_snd_data_hotel_3f_f_sdb__name[35];
fsFile data_sound_snd_data_hotel_3f_f_sdb__info[1];
fsFileIndex data_sound_snd_data_hotel_3f_f_sdb[1];
char data_sound_snd_data_hotel_bf_b_sdb__name[35];
fsFile data_sound_snd_data_hotel_bf_b_sdb__info[1];
fsFileIndex data_sound_snd_data_hotel_bf_b_sdb[1];
char data_sound_snd_data_hotel_bf_f_sdb__name[35];
fsFile data_sound_snd_data_hotel_bf_f_sdb__info[1];
fsFileIndex data_sound_snd_data_hotel_bf_f_sdb[1];
char data_sound_snd_data_hotel_fire_sdb__name[35];
fsFile data_sound_snd_data_hotel_fire_sdb__info[1];
fsFileIndex data_sound_snd_data_hotel_fire_sdb[1];
char data_sound_snd_data_hp_sdb__name[27];
fsFile data_sound_snd_data_hp_sdb__info[1];
fsFileIndex data_sound_snd_data_hp_sdb[1];
char data_sound_snd_data_labyrinth_e_sdb__name[36];
fsFile data_sound_snd_data_labyrinth_e_sdb__info[1];
fsFileIndex data_sound_snd_data_labyrinth_e_sdb[1];
char data_sound_snd_data_labyrinth_n_sdb__name[36];
fsFile data_sound_snd_data_labyrinth_n_sdb__info[1];
fsFileIndex data_sound_snd_data_labyrinth_n_sdb[1];
char data_sound_snd_data_labyrinth_w_sdb__name[36];
fsFile data_sound_snd_data_labyrinth_w_sdb__info[1];
fsFileIndex data_sound_snd_data_labyrinth_w_sdb[1];
char data_sound_snd_data_lake_sdb__name[29];
fsFile data_sound_snd_data_lake_sdb__info[1];
fsFileIndex data_sound_snd_data_lake_sdb[1];
char data_sound_snd_data_null_sdb__name[29];
fsFile data_sound_snd_data_null_sdb__info[1];
fsFileIndex data_sound_snd_data_null_sdb[1];
char data_sound_snd_data_ob_sdb__name[27];
fsFile data_sound_snd_data_ob_sdb__info[1];
fsFileIndex data_sound_snd_data_ob_sdb[1];
char data_sound_snd_data_observation_sdb__name[36];
fsFile data_sound_snd_data_observation_sdb__info[1];
fsFileIndex data_sound_snd_data_observation_sdb[1];
char data_sound_snd_data_prison_bf_sdb__name[34];
fsFile data_sound_snd_data_prison_bf_sdb__info[1];
fsFileIndex data_sound_snd_data_prison_bf_sdb[1];
char data_sound_snd_data_prison_n_sdb__name[33];
fsFile data_sound_snd_data_prison_n_sdb__info[1];
fsFileIndex data_sound_snd_data_prison_n_sdb[1];
char data_sound_snd_data_prison_s_sdb__name[33];
fsFile data_sound_snd_data_prison_s_sdb__info[1];
fsFileIndex data_sound_snd_data_prison_s_sdb[1];
char data_sound_snd_data_ps_sdb__name[27];
fsFile data_sound_snd_data_ps_sdb__info[1];
fsFileIndex data_sound_snd_data_ps_sdb[1];
char data_sound_snd_data_qp_sdb__name[27];
fsFile data_sound_snd_data_qp_sdb__info[1];
fsFileIndex data_sound_snd_data_qp_sdb[1];
char data_sound_snd_data_rr_sdb__name[27];
fsFile data_sound_snd_data_rr_sdb__info[1];
fsFileIndex data_sound_snd_data_rr_sdb[1];
char data_sound_snd_data_ru_sdb__name[27];
fsFile data_sound_snd_data_ru_sdb__info[1];
fsFileIndex data_sound_snd_data_ru_sdb[1];
char data_sound_snd_data_society_sdb__name[32];
fsFile data_sound_snd_data_society_sdb__info[1];
fsFileIndex data_sound_snd_data_society_sdb[1];
char data_sound_snd_data_tgs_trial_sdb__name[34];
fsFile data_sound_snd_data_tgs_trial_sdb__info[1];
fsFileIndex data_sound_snd_data_tgs_trial_sdb[1];
char data_sound_snd_data_th_sdb__name[27];
fsFile data_sound_snd_data_th_sdb__info[1];
fsFileIndex data_sound_snd_data_th_sdb[1];
char data_sound_snd_data_to_heaven_sdb__name[34];
fsFile data_sound_snd_data_to_heaven_sdb__info[1];
fsFileIndex data_sound_snd_data_to_heaven_sdb[1];
char data_sound_snd_data_toilet_sdb__name[31];
fsFile data_sound_snd_data_toilet_sdb__info[1];
fsFileIndex data_sound_snd_data_toilet_sdb[1];
char data_sound_snd_data_town_east_sdb__name[34];
fsFile data_sound_snd_data_town_east_sdb__info[1];
fsFileIndex data_sound_snd_data_town_east_sdb[1];
char data_sound_snd_data_town_west_sdb__name[34];
fsFile data_sound_snd_data_town_west_sdb__info[1];
fsFileIndex data_sound_snd_data_town_west_sdb[1];


